<?php

namespace Blog\View;

use Web\View\SimpleView;

class BlogFrontView extends SimpleView {


    // on "wrap" le contenu dans un "root_modele" qui contient les balises HTML de base
    public function render()
    {
        // 1 - rendu de la vue simple
        $html_content = parent::render(); // TODO: Change the autogenerated stub

        // 2 - rendu dun contenu inséré dans le root modele
        $wrapper_data = array(
            "html_content" => $html_content
        );
        
        $wrapper = new SimpleView("root_model",$wrapper_data);
        return $wrapper -> render();
    }
}