
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <hr class="small">
                        <span class="subheading">(<?php echo date("d/m/Y H:i:s"); ?>) A Clean Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <?php
                /** @var \Model\PostModel $post */
                foreach($posts as $post):?>
                <div class="post-preview">
                    <a href="/post/<?= $post -> id ?>">
                        <h2 class="post-title">
                            <?= $post -> sujet ?>
                        </h2>
<!--                        <h3 class="post-subtitle">-->
<!--                        </h3>-->
                    </a><?= $post -> sujet ?>
                    <p class="post-meta">Posted by <a href="#"><?= ucfirst(strtolower($post -> auteur -> prenom)).' '.strtoupper(substr($post -> auteur -> nom ,0,1))."." ?></a> on <?= $post -> date_post ?></p>
                </div>
                <hr>
                <?php endforeach; ?>
                
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    