
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/post-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>Man must explore, and this is exploration at its greatest</h1>
                        <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                        <span class="meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <?php
                /** @var \Web\Blog\Models\Post $post */
                foreach($posts as $post):?>
                <div class="post-preview">
                    <a href="/post/<?= $post -> id ?>">
                        <h2 class="post-title">
                            <?= $post -> titre ?>
                        </h2>
                        <h3 class="post-subtitle">
                            <?= $post -> soustitre ?>
                        </h3>
                    </a><?= $post -> titre ?>
                    <p class="post-meta">Posted by <a href="#"><?= $post -> posted_by ?></a> on <?= $post -> posted_at ?></p>
                </div>
                <hr>
                <?php endforeach; ?>
                
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    