<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/">Home</a>
        </li>
        <li>
            <a href="/about">About</a>
        </li>
        <li>
            <a href="/le-blog">le blog </a>
        </li>
        <li>
            <a href="/contact">Contact</a>
        </li>
        <li>
            <?php if($service_user -> isConnected()):?>
            <a href="/logout">Déconnexion
                <br><small>(<?php echo $service_user -> getEmail() ?>)</small>
            </a>
            <?php else: ?>
            <a href="/login">Connexion</a>
            <?php endif ?>
        </li>
    </ul>
</div>