<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/">Home</a>
        </li>
        <li>
            <a href="/about">About</a>
        </li>
        <li>
            <a href="/le-blog">exemple de post</a>
        </li>
        <li>
            <a href="/contactez-nous">Contact</a>
        </li>
    </ul>
</div>