<header class="intro-header" style="background-image: url('img/home-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading">
                    <h1>Accueil de votre espace privé</h1>
                    <hr class="small">
                    <span class="subheading">informations sensibles...</span>
                </div>
            </div>
        </div>
    </div>
</header>