<div class="post-preview">
    <a href="/post/<?= $post -> id ?>">
        <h2 class="post-title">
            <?= $post -> sujet ?>
        </h2>
        <!--                        <h3 class="post-subtitle">-->
        <!--                        </h3>-->
    </a><?= $post -> sujet ?>
    <p class="post-meta">Posted by <a href="/auteur/<?= $post -> auteur -> id ?>"><?= ucfirst(strtolower($post -> auteur -> prenom)).' '.strtoupper(substr($post -> auteur -> nom ,0,1))."." ?></a> on <?= $post -> date_post ?></p>
</div>
<hr>